# Generated by Django 2.1.7 on 2019-04-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0004_auto_20190414_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='interfaces',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
